#!/bin/zsh

find . -name \*.pyc -delete
nosetests --rednose --with-coverage --cover-package=transip
# There is no version of pylint that covers Python 2.7 and 3.4 - 3.8.
# echo "------------------------------------------------------"
# pylint --rcfile=.pylintrc transip
